sudo: false

language: php

env:
  - DB=MYSQL CORE_RELEASE=4.0
  
matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=MYSQL PHPUNIT_TEST=1 CORE_RELEASE=4.0
    - php: 7.0
      env: DB=MYSQL PHPUNIT_TEST=1 CORE_RELEASE=4.0
    - php: 7.1
      env: DB=MYSQL PHPUNIT_TEST=1 CORE_RELEASE=4.0
      
before_script:
  - composer self-update || true
  - phpenv rehash
  - phpenv config-rm xdebug.ini

# Install composer dependencies
  - export PATH=~/.composer/vendor/bin:$PATH
  - composer install --prefer-dist
  - composer require --prefer-dist --no-update symfony/config:^3.2 silverstripe/framework:4.0.0 silverstripe/config:1.0.0 --prefer-dist
  - composer update
  
script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  
branches:
  only:
    - master
