Injector:
  SentryClient:
    class: SilverStripeSentry\Adaptors\RavenClient
    # Installs all available PHP error handlers
    # Untested when set to true
    install: false
  SentryLogWriter:
    class: SilverStripeSentry\SentryLogWriter

