---
Name: silverstripe-sentry
After:
  - 'framework/*'
  - 'cms/*'
---

phptek\Sentry\SentryLogWriter:
  dependencies:
    client: %$SentryClientAdaptor
    
phptek\Sentry\Adaptor\RavenClient:
  # Installs all available PHP error handlers
  # Untested when set to true
  install: false

Injector:
  SentryLogWriter:
    class: phptek\Sentry\SentryLogWriter
  SentryClientAdaptor:
    class: phptek\Sentry\Adaptor\RavenClient
