---
Name: sentry
---

PhpTek\Sentry\Log\SentryLogger:
  dependencies:
    client: %$PhpTek\Sentry\Adaptor\RavenClient
    
PhpTek\Sentry\Adaptor\RavenClient:
  # Installs all available PHP error handlers
  # Untested when set to true
  install: false

SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      - [ pushHandler, [ %$PhpTek\Sentry\Handler\SentryMonologHandler ]]
