---
Name: silverstripe-sentry
After:
  - 'framework/*'
  - 'cms/*'
---

SilverStripeSentry\SentryLogWriter:
  dependencies:
    client: %$SentryClientAdaptor
    
SilverStripeSentry\Adaptor\RavenClient:
  # Installs all available PHP error handlers
  # Untested when set to true
  install: false

Injector:
  SentryLogWriter:
    class: SilverStripeSentry\SentryLogWriter
  SentryClientAdaptor:
    class: SilverStripeSentry\Adaptor\RavenClient
