---
Name: sentry-config
---

PhpTek\Sentry\Log\SentryLogger:
  dependencies:
    client: %$PhpTek\Sentry\Adaptor\SentryAdaptor

SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      - [ pushHandler, [ %$PhpTek\Sentry\Handler\SentryHandler ]]