---
Name: sentry-config
---

PhpTek\Sentry\Log\SentryLogger:
  dependencies:
    adaptor: '%$PhpTek\Sentry\Adaptor\SentryAdaptor'

SilverStripe\Core\Injector\Injector:
  Monolog\Logger:
    calls:
      - [ pushHandler, [ '%$PhpTek\Sentry\Handler\SentryHandler' ]]
